### ISSUE TITLE
問題追加依頼

### ISSUE THREAD

**Issue by JpnLavender** [mystasly48/ProgrammingQuestion#24]
ある文字列(s)が一行目に入力されてきます次に、ある文字(c)が二行目で入力されてきます。
その文字列が、ある文字列(s)に含まれているかtrue || false で出力してください

入力フォーマット

```
s
c
```

入力例1

```
oppai
i
```

出力例

```
true
```

入力例2

```
oppai
z
```

出力例

```
false
```

見本

```ruby
puts (gets =~ /#{gets}/ ? true : false)
```

**Comment by mystasly48** [comment]
新問題のご提供ありがとうございます。
以下のような内容でよろしいでしょうか？

---

１行目に文字列(s)、２行目に文字(c)が入力されます。
文字列(s)に文字(c)が含まれていた場合には true、 含まれていなかった場合には false と出力してください。

形式
```
s
c
```

入力例1
```
programming
a
```

出力例1
```
true
```

入力例2
```
github
o
```

出力例2
```
false
```

**Comment by JpnLavender** [comment]
大丈夫だと思います！

**Comment by mystasly48** [comment]
```ruby
puts (gets =~ /#{gets}/ ? true : false)
```
のコードで
```
programming
a
```
と入力してみたところ
```
false
```
と出力されてしまいました。

**Comment by JpnLavender** [comment]
```ruby
puts (gets.chomp =~ /#{gets.chomp}/ ? true : false)
```

こうでしたね

**Comment by mystasly48** [comment]
[Part6](https://github.com/mystasly48/ProgrammingQuestion/tree/master/Part6) 問題を公開しました。
問題のご提供ありがとうございました！

**Comment by JpnLavender** [comment]
💩
