### ISSUE TITLE
問題追加依頼

### ISSUE THREAD

**Issue by JpnLavender** [mystasly48/ProgrammingQuestion#25]
"ズン"と4回入力されたあと5回目に"ドコ"と入力されたら"キヨシ!"と出力してください

**Comment by mystasly48** [comment]
```
ズン
ズン
ズン
ズン
ドコ
```
と入力された場合には
```
キヨシ！
```
と出力させ、

```
ズン
ズン
ズン
ズン
```
だけの入力であれば無視、ということでしょうか？

**Comment by JpnLavender** [comment]
ですん

**Comment by mystasly48** [comment]
それ以外に入力の条件などはありますでしょうか？

**Comment by JpnLavender** [comment]
いえ。無いです💩

**Comment by mystasly48** [comment]
ありがとうございます。
以下のような内容でよろしいでしょうか？

---

改行区切りで`ズン`と４回入力されたあとに`ドコ`と入力されていれば`キヨシ！`と出力させてください。
`ドコ`が入力されていなかった場合には無視してください。

入力例1
```
ズン
ズン
ズン
ズン
ドコ
```

出力例1
```
キヨシ！
```

入力例2
```
ズン
ズン
ズン
ズン
```

出力例2
```
```

**Comment by JpnLavender** [comment]
大丈夫です💩

**Comment by mystasly48** [comment]
解答例を書いてて思ったのですが、コンソールだとどのタイミングで「入力しない」と判定されたのか分からず、５行目で処理が止まってしまいますね。実装寸前まで行きましたが、無理そうです・・・。

**Comment by JpnLavender** [comment]
僕の方で実装できましたよ？

```crystal
 class Application

   def main : String
     while true
       next unless zun_processing
       next unless doco_processing
       puts "キヨシ"
     end
   end

   def doco_processing : Bool
     puts ""
     gets.to_s.chomp == "ドコ" ? true : false
   end

   def zun_processing : Bool
     i = 0
     while true
       i += 1 if gets.to_s.chomp == "ズン"
       break if i >= 4
     end
     return true
   end

 end

 Application.new.main
```

**Comment by JpnLavender** [comment]
実行してないですけど 一応Ruby

```ruby
class Application

   def main
     while true
       next unless zun_processing
       next unless doco_processing
       puts "キヨシ"
     end
   end

   def doco_processing
     gets.chomp == "ドコ" ? true : false
   end

   def zun_processing
     i = 0
     while true
       i += 1 if gets.chomp == "ズン"
       break if i >= 4
     end
     return true
   end

 end

 Application.new.main

```

**Comment by mystasly48** [comment]
Ruby の実行環境はあるので試してみましたがいつまでも入力待ちです

**Comment by JpnLavender** [comment]
入力待ちっていうのは、ズンズンズンズンってきたあとキヨシってくるのを待ってるってことですか？

それって仕様でいい気が

**Comment by JpnLavender** [comment]
ズン(入力)
ズン(入力)
ズン(入力)
ドコ(入力)
キヨシ(出力)
って感じでいいと。。。
ちゃんと終わらせたいのなら、キヨシのあとにexitしちゃえば良いのでは？

**Comment by mystasly48** [comment]
えぇと、
```
ズン
ズン
ズン
ズン
ドコ
```
と入力されるか
```
ズン
ズン
ズン
ズン
```
とだけ入力されるか、だと思っていたのですが、違ったようですか？

入力の回数は確定させておいたほうが良いですね。

**Comment by JpnLavender** [comment]
僕の方は4回1回で固定？されていますよ？
ただ途中で変なのいれるとカウントがリセットされますが

何のこと言いたいのかちょっと理解できてるか自信ないですが

**Comment by JpnLavender** [comment]
```ruby
class Application

   def main
     while true
       next unless zun_processing
       next unless doco_processing
       puts "キヨシ"
     end
   end

   def doco_processing
     gets.chomp == "ドコ" ? true : false
   end

   def zun_processing
     i = 0
     while true
       i += 1 if gets.chomp == "ズン"
       p i 
       break if i >= 4
     end
     return true
   end

 end

 Application.new.main

```

こうしてみると動きがわかるのではないでしょうか

**Comment by mystasly48** [comment]
ドコのあるパターンとないパターンの入出力結果をスクリーンショットで貼り付けていただくことは可能でしょうか。

**Comment by JpnLavender** [comment]
![2016-11-12 16 31 08](https://cloud.githubusercontent.com/assets/12014002/20236362/70c1f650-a8f5-11e6-9179-b88101c4ed69.png)

**Comment by JpnLavender** [comment]
(◎)
ズン
ズン
ズン
ズン
ドコ
キヨシ!(勝手に出力)

(☓)
ズン
ズン
ズン
ズン
ねこ(ズンのカウントが0になる)

(☓)
ズン
ズン
ねこ(異物が混入してるけどまあOK)(コレで0にしてもいいけど初心者向けじゃなくなる気がするので)
ズン
ズン
ドコ
キヨシ!(勝手に出力)

**Comment by JpnLavender** [comment]
あ。最初の方で

```
ズン
ズン
ズン
ズン
```
だけの入力であれば無視、ということでしょうか？

って質問に対して僕が「ですん」と、適当な反応してますが
これ、全然「ですん」じゃないですね(意味は理解してたけど此処で適当な解釈してた)
コレを無視するって、難しくはないですが、正直めんどくさいので
普通に5回目の処理で、適当な値の場合無視するって意味だったんですよ。。。

**Comment by mystasly48** [comment]
５回目が、「ドコ」であれば、「キヨシ！」。それ以外であれば、無視。ということですね！
サンプルコードが無限ループになってるようですが、５回の入力に１回の出力で終わらせれば良さそうですね。
ありがとうございます。

**Comment by JpnLavender** [comment]
すみません、体調悪いのと私事で頭回ってなかったです＞＜・・・

**Comment by mystasly48** [comment]
問題内容を少々変更してみました。

## 問題内容
改行区切りで`ズン`と４回入力されたあとに`ドコ`と入力されたら`キヨシ！`、その他が入力されたら`ズコー！`と出力してください。

## 入力形式
```
s
s
s
s
t
```

## 入出力例

入力1  
```
ズン
ズン
ズン
ズン
ドコ
```

出力1  
```
キヨシ！
```

入力2  
```
ズン
ズン
ズン
ズン
ポコ
```

出力2  
```
ズコー！
```

**Comment by JpnLavender** [comment]
いいですね！こう言う風にすればよかったですね！

**Comment by mystasly48** [comment]
ありがとうございます。
[Part7](https://github.com/mystasly48/ProgrammingQUestion/blob/master/Part7/) 問題を追加しました。
問題のご提供ありがとうございました！

**Comment by JpnLavender** [comment]
💩
