### ISSUE TITLE
問題追加の提案

### ISSUE THREAD

**Issue by JpnLavender** [mystasly48/ProgrammingQuestion#35]
ある文字列が２つ入力されますその値を比較して、重複している値の数を出力してください
(最初に入力される値に'w'が3つ次に入力される値に'w'が1つの場合は'1'とカウントしてください

入力フォーマット

```
s1
s2
```

入力例1
```
test
tech
```

出力例1
```
2
```

入力例2
```
date
data
```

出力例2
```
3
```

入力例3
```
linux
unix
```

出力例3
```
4
```

入力例4
```
Apple
Minecrosoft
```

出力例4
```
1
```

**Comment by JpnLavender** [comment]
@mystasly48 新しい問題を思いついたのでご確認お願い致します

**Comment by mystasly48** [comment]
１行目に文字列(s)、２行目に文字列(t)が入力されます。
文字列(s)と文字列(t)を比較して、一致している文字数を出力してください。
なお、重複は除くものとします。

入力形式
s
t

入力例1
test
tech

出力例1
2

入力例2
linux
unix

出力例2
4

入力例3
PPAP
PPAP

出力例3
2

**Comment by mystasly48** [comment]
追加しました！
問題のご提供ありがとうございました！
