### ISSUE TITLE
Add Question Reqest

### ISSUE THREAD

**Issue by JpnLavender** [mystasly48/ProgrammingQuestion#39]
複数の数字が、スペース区切りで、複数個入力されます。その中で一番小さい数字と大きい数字をスペース区切りで並べて出力してください

入力フォーマット
~~~
c
i_1 i_2 ....
~~~

出力フォーマット
~~~
min max
~~~

入力例1

~~~
3
23 1 90
~~~

出力例1

~~~
1 90
~~~

入力例2

~~~
2
10 9
~~~

出力例2

~~~
9 10
~~~

入力例3

~~~
10
30 78 39 10 40 12 34 76 85 48
~~~

出力例3

~~~
10 85
~~~

**Comment by mystasly48** [comment]
シンプルでとても良い問題ですね！

入力形式が
```
c
i_1 i_2 ...
```
となっていますが、
```
n
i_1 i_2 ... i_n
```
という認識でよろしいでしょうか？

**Comment by JpnLavender** [comment]
はい！大丈夫です＞＜

**Comment by mystasly48** [comment]
わかりました！
問題の作成に取り掛からせていただきます :octocat:

**Comment by mystasly48** [comment]
[Part9 問題](https://github.com/mystasly48/ProgrammingQuestion/tree/master/Part9) を追加しました！
問題のご提供ありがとうございます :octocat:
