### ISSUE TITLE
筆算しよう！

### ISSUE THREAD

**Issue by karen1019** [mystasly48/ProgrammingQuestion#57]
```
問題内容
1行目と2行目に2桁の整数が入力されるのでそれを筆算してください。

入出力例

入力1
91
41

出力1
  91
 *41
----
  91
364
----
3731


入力2
14
45

出力2
  14
 *45
----
  70
 56
----
 630


入力3
10
10

出力3
  10
 *10
----
   0
 10
----
 100
```

**Comment by mystasly48** [comment]
大変遅れてしまい申し訳ありません。このような感じでよろしいでしょうか？
-----

# 第#問 - Part#

## 問題内容
１行目と２行目の２行に渡って、２桁の整数が入力されます。
この２つの数字を筆算の形式で掛け算をして出力してください。

## 入力条件
```
10 <= N < 100
10 <= M < 100
```

## 入出力形式

### 入力形式
```
N
M
```

### 出力形式
```
   N
 * M
----
  ..
 ..
----
prod
```

## 入出力例

### 例 1
```
10
10
```

出力例
```
  10
 *10
----
   0
 10
----
 100
```

### 例 2
入力例
```
14
45
```

出力例
```
3 1 0 1
```

### 例 3
入力例
```
91
41
```

出力例
```
  91
 *41
----
  91
364
----
3731
```

**Comment by mystasly48** [comment]
**入力例１**についてなのですが、
0*0=0, 0*1=0 で 00 とするか、 0 とするか、のどちらにしましょうか。
個人的には前者の「ゼロ埋め」をしたいところではあります。

**Comment by mystasly48** [comment]
`0 * 0 == 0, 0 * 1 = 0, 00` とするようにしました。
ゼロ埋めでほんの少し難易度が上がりますが、これもおもしろいでしょう！
