### ISSUE TITLE
文字の中から異なる文字の座標を探し出そう

### ISSUE THREAD

**Issue by JpnLavender** [mystasly48/ProgrammingQuestion#74]
**フォーマットをrawでコピーできなかったからご了承ください**

#文字ブロックの中から異なる文字の座標を出力してください

入力

~~~
3 5
...
...
...
.,.
...
~~~

出力

~~~
2 4
~~~

入力

~~~
5 7
髪髪髪髪髪
髪髪髪髪髪
髪髪髪髪髪
髪髪髪髪髪
髪髪髪髪髪
髪髪神髪髪
髪髪髪髪髪
髪髪髪髪髪
~~~

出力

~~~
3 6
~~~

入力

~~~
5 8
😉😉😉😉😉
😉😉😉😉😉
😉😀😉😉😉
😉😉😉😉😉
😉😉😉😉😉
😉😉😉😉😉
😉😉😉😉😉
😉😉😉😉😉
~~~

出力

~~~
2 3
~~~

**Comment by JpnLavender** [comment]
フォーマットや入力上限は設定していただけると嬉しいです
問題提供というよりはアイディア定量って形で...許してください

**Comment by mystasly48** [comment]
こんな感じではどうでしょうか。
入力条件に少し悩みましたが・・・。

-----

# 第１２問 - Part12

## 問題内容
１行目にスペース区切りで整数（w）と整数（h）が入力されます。

次に改行区切りで h行、スペース区切りで w列 の文字（c）が入力されます。

c はどこかだけが違う文字になっています。

その違う文字の座標を x y のスペース区切りで出力してください。(result_x result_y)

## 入力条件
```
0 < w < 10000
0 < h < 10000
c は文字（１文字）で、１文字以外すべて同じになっています。
```

## 入出力形式

### 入力形式
```
w h
h1_w1 h1_w2 ... h1_w
h2_w1 h2_w2 ... h2_w
...
h_w1 h_w2 ... h_w
```

### 出力形式
```
result_x result_y
```

## 入出力例

### 例 1
入力例
```
3 3
aaa
aba
aaa
``` 

出力例
```
2 2
```

### 例 2
入力例
```
6 6
111111
111111
111111
111119
111111
111111
```
 
出力例    
``` 
4 6
```

### 例３
入力例
```
1 1
o
```

出力例
```
1 1
```

**Comment by JpnLavender** [comment]
いいですね！！こんな感じって想像していたのと全く一緒です！ありがとうございます😊

**Comment by mystasly48** [comment]
よかったです:sushi: 明日、配信します。

**Comment by mystasly48** [comment]
追加しました！ [Part12](https://github.com/mystasly48/ProgrammingQuestion/tree/master/Part12)
