### ISSUE TITLE
お釣りの計算

### ISSUE THREAD

**Issue by mystasly48** [mystasly48/ProgrammingQuestion#77]

**Comment by kzdw** [comment]
why not write it in English? 
Japanese is hard to understand .

**Comment by mystasly48** [comment]
I'm a japanese speaker... That's why........
Sorry, I have no plans for support to English.

**Comment by mystasly48** [comment]
・**投入する金額**の上限および下限。（現時点では、`0 <= P <= 10000` の予定）
・**購入する商品の金額**の上限および下限。（現時点では、`100 <= M <= 500` の予定）
・**購入する商品の個数**の上限および下限。（現時点では、`N == 1` の予定）

**Comment by mystasly48** [comment]
# 第１３問 - Part13

## 問題内容
自動販売機の釣銭の計算問題です。

１行目に投入された金額が入力されます。(b)
２行目に購入する商品の個数が入力されます。(N)
２行目以降に購入した商品の金額が改行区切りでn行入力されます。(p)

１０円玉、５０円玉、１００円玉、５００円玉を使用して、１番少ない枚数で釣銭を計算してください。
出力はスペース区切りで、１０円玉、５０円玉、１００円玉、５００円玉の順に枚数を出力してください。
また、０枚の場合には 0 と出力してください。

## 入力条件
```
0 < N <= 10
0 < b <= 10000
0 < p <= 1000
投入金額が足りなくなることはありません。
b, p は必ず１０の倍数の値になります。
```

## 入出力形式

### 入力形式
```
b
N
p_1
P_2
...
p_N
```

### 出力形式
```
ten_coin fiftenn_coin hundred_coin tenhundred_coin
```

## 入出力例

### 例 1
入力例
```
150
1
120
```

出力例
```
3 0 0 0
```

### 例 2
入力例
```
1000
3
150
150
120
```

出力例
```
3 1 0 1
```

### 例 3
入力例
```
10000
10
980
530
600
350
260
170
80
890
710
590
```

出力例
```
4 0 3 9
```

**Comment by mystasly48** [comment]
自動販売機にこだわる必要はないのでは、ということで、ただの釣銭の計算の問題にします。

**Comment by mystasly48** [comment]
# 第１３問 - Part13

## 問題内容
１行目に投入する金額が入力されます。(b)
２行目に購入する商品の個数が入力されます。(N)
３行目から改行区切りでN行、購入した商品の金額が入力されます、(p)

１円玉、５円玉、１０円玉、５０円玉、１００円玉、５００円玉、１０００円札、５０００円札を使用して、１番少ない枚数でお釣りを計算してください。
出力はスペース区切りで、５０００円札、１０００円札・・・５円玉、１円玉と大きい金額の順に枚数を出力してください。

## 入力条件
```
0 < b <= 10000
0 < N <= 10
0 < p <= 10000
投入金額が足りなくなることはありません。
```

## 入出力形式

### 入力形式
```
b
N
p_1
P_2
...
p_N
```

### 出力形式
```
five_thousand one_thousand five_hundred one_hundred fifteen ten five one
```

## 入出力例

### 例 1
入力例
```
200
1
108
```

出力例
```
0 0 0 0 1 4 0 2
```

### 例 2
入力例
```
2000
3
216
432
864
```

出力例
```
0 0 0 4 1 3 1 3
```

### 例 3
入力例
```
10000
10
1058
572
648
378
280
183
86
961
766
637
5569
4431
```

出力例
```
0 4 0 4 0 3 0 1
```
