### ISSUE TITLE
問題追加希望

### ISSUE THREAD

**Issue by JpnLavender** [mystasly48/ProgrammingQuestion#9]
あなたは、あなたの友達と自分の車で、旅行に行くことになりました。
まず、行く場所までの距離(k)と、あなたの乗ってる車のリッター(l)がスペース区切りで
入力されます

貴方の友達は、合計で(n)人です(これは二回目の入力で与えられます)
同時にスペース区切りで今のリッター当たりの金額が入力されます(m)
友達全員は、旅行でかかった往復のガソリン代を払うと言って居ます、往復でかかった1人あたりの
金額を小数点切り捨てで出力してください

入力フォーマット

```
k l
n m
```

入力例

```
600 15
4 120
```

出力例
```
1920
```

入力例

```
333 7
3 111
```

出力例
```
2442
```

Rubyコード例

```ruby
v = gets.split(' ')
k = gets.split(' ')

a = v[0].to_i / v[1].to_i
b = k[0].to_i + 1
puts a / b * k[1].to_i * 2
```

```ruby
a = []
2.times{ a << gets.split(' ').map(&:to_i) }
puts (((a[0][0] / a[0][1]) / (a[1][0] + 1) * a[1][1])) * 2
```

```ruby
def g
  gets.split(' ').map(&:to_i)
end
puts((v,k=g,g)[0][0]/v[1]/(k[0]+1)*k[1]*2)
```

```ruby
puts((v,k=gets.split(' ').map(&:to_i),gets.split(' ').map(&:to_i))[0][0]/v[1]/(k[0]+1)*k[1]*2)
```

**Comment by JpnLavender** [comment]
![寿司ゆき:sorry](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/05.png)

**Comment by JpnLavender** [comment]
![LGTM](https://lgtm.in/p/KT22Dq9iq)

**Comment by mystasly48** [comment]
ちょっと修正してみたのですが、どうでしょうか。
入力が２行必要あるかなと思い１行にしてしまったのですが・・・。
また、フォーマットの変数名についても `n, k, l` は良さそうだったのですが `m` がどうかなと思いまして。

--

あなたは車で友達と旅行に行くことになりました。
友達は往復のガソリン代を割り勘で払おうと言ってくれています。
１人あたりのガソリン代を小数点以下を切り捨てて出力してください。

友達の人数、目的地までの距離（km）、車の燃費（km/L）、ガソリンの値段（円/L）がスペース区切りで入力されます。

入力例
`3 100 10 110`

出力例
`550`

入力例
`5 573 17 124`

出力例
`1392`

**Comment by JpnLavender** [comment]
良いんじゃないでしょうか
![寿司ゆき:happy](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/24.png)

**Comment by mystasly48** [comment]
[Part4 問題](https://github.com/mystasly48/ProgrammingQuestion/tree/master/Part4) を追加しました。
問題のご提供ありがとうございました。
